### PR TITLE
#173615157 user signup

### PR DESCRIPTION
**Pull request by blaise82**
#### What does this PR do?
- user sign up

#### Description of Task to be completed?
- set up controllers
- set up routes
- validate data

#### How should this be manually tested?
- clone this repo `git clonehttps://github.com/Ntare22/iguru-backend`
- run `npm install`
- run `npm run dev` to start the dev environment

Route:  http://localhost:8080/api/v1/auth/signup
```
 {
    "firstName": "",
    "lastName": "",
    "email": "",
    "password": ""
}
```
[finishes #173615157]

### CODE REVIEW

**Review by Ntare22 — COMMENTED** [review]
Just setup swagger... remember to add swagger documentation...
Did not put a description. Let me know if you cannot figure it out!

**Comment by blaise82** [comment]
> Just setup swagger... remember to add swagger documentation...
> Did not put a description. Let me know if you cannot figure it out!

great bro
you know we could also have used a postman docx

**Comment by Ntare22** [comment]
> > Just setup swagger... remember to add swagger documentation...
> > Did not put a description. Let me know if you cannot figure it out!
> 
> great bro
> you know we could also have used a postman docx

Please use swagger, I've already installed it and it is quite straight forwared

**Comment by blaise82** [comment]
> > > Just setup swagger... remember to add swagger documentation...
> > > Did not put a description. Let me know if you cannot figure it out!
> > 
> > great bro
> > you know we could also have used a postman docx
> 
> Please use swagger, I've already installed it and it is quite straight forwared

Yeah I use swagger. 
Note: swagger wasn't working right so I had to change it's settings

As you can see this PR is marked ready please when you get time review it. Comment or merge it.

**Comment by Ntare22** [comment]
> > > > Just setup swagger... remember to add swagger documentation...
> > > > Did not put a description. Let me know if you cannot figure it out!
> > > 
> > > 
> > > great bro
> > > you know we could also have used a postman docx
> > 
> > 
> > Please use swagger, I've already installed it and it is quite straight forwared
> 
> Yeah I use swagger.
> Note: swagger wasn't working right so I had to change it's settings
> 
> As you can see this PR is marked ready please when you get time review it. Comment or merge it.



> > > > Just setup swagger... remember to add swagger documentation...
> > > > Did not put a description. Let me know if you cannot figure it out!
> > > 
> > > 
> > > great bro
> > > you know we could also have used a postman docx
> > 
> > 
> > Please use swagger, I've already installed it and it is quite straight forwared
> 
> Yeah I use swagger.
> Note: swagger wasn't working right so I had to change it's settings
> 
> As you can see this PR is marked ready please when you get time review it. Comment or merge it.

**Comment by Ntare22** [comment]
> > > > Just setup swagger... remember to add swagger documentation...
> > > > Did not put a description. Let me know if you cannot figure it out!
> > > 
> > > 
> > > great bro
> > > you know we could also have used a postman docx
> > 
> > 
> > Please use swagger, I've already installed it and it is quite straight forwared
> 
> Yeah I use swagger.
> Note: swagger wasn't working right so I had to change it's settings
> 
> As you can see this PR is marked ready please when you get time review it. Comment or merge it.

It was working... its just because I set it up different!

**Pull request closed without merging**
